<<<<<<< HEAD
spring:
  application:
    name: zuul
    
server:  port: 3001
  
eureka:  client:    service-url:      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka

#zuul:
#  routes:#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**

zuul:
  retryable: true
  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
    
=======
spring:
  application:
    name: zuul
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka

zuul:
  retryable: true

#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 500
            
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

>>>>>>> branch 'master' of https://github.com/ZX18686290191/GIT2.git
